import js from '@eslint/js';
import globals from 'globals';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import {
  CAMPAIGN_MODEL_IMPORT_PATTERNS,
  FSD_BOUNDARY_PLUGIN,
  FSD_PUBLIC_API_PATTERNS,
  REFERENCE_LOADER_IMPORT_PATTERNS,
  SHARED_MODAL_PUBLIC_API_PATTERN,
  TYPESCRIPT_PUBLIC_API_PATTERNS,
} from './scripts/eslint-import-boundaries.mjs';

export default [
  { ignores: ['dist', 'node_modules', 'data'] },
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.serviceworker,
      },
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    settings: { react: { version: '18.3' } },
    plugins: {
      react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      'react/jsx-no-target-blank': 'off',
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      'react/prop-types': 'off',
      'no-unused-vars': ['warn', { 
        'vars': 'all', 
        'args': 'after-used', 
        'ignoreRestSiblings': true,
        'argsIgnorePattern': '^_' 
      }],
      'no-console': ['warn', { allow: ['warn', 'error', 'info', 'log'] }],
      'no-restricted-imports': ['error', {
        patterns: [
          ...FSD_PUBLIC_API_PATTERNS,
          SHARED_MODAL_PUBLIC_API_PATTERN,
          {
            group: ['**/features/images/api/*', '**/features/images/model/*', '**/features/images/ui/*'],
            message: 'Import the images slice through features/images/index.js.',
          },
          {
            group: ['**/features/dice/ui/*', '**/features/dice/model/*'],
            message: 'Import the dice feature through features/dice/index.js.',
          },
          {
            group: ['**/features/rules-reference/ui/*', '**/features/rules-reference/model/*'],
            message: 'Import rules-reference behavior through features/rules-reference/index.js.',
          },
          {
            group: ['**/features/entity-link/ui/*', '**/features/entity-link/model/*'],
            message: 'Import entity-link behavior through features/entity-link/index.js.',
          },
          {
            group: ['**/features/campaign-create/ui/*'],
            message: 'Import campaign creation UI through features/campaign-create/index.js.',
          },
          {
            group: ['**/features/player-questions/ui/*'],
            message: 'Import player questions UI through features/player-questions/index.js.',
          },
          {
            group: [
              '**/features/ai-edit-monster/ui/*',
              '**/features/ai-edit-monster/model',
              '**/features/ai-edit-monster/model.ts',
            ],
            message: 'Import AI monster editing through features/ai-edit-monster/index.js.',
          },
          {
            group: [
              '**/features/edit-monster/ui/*',
              '**/features/edit-monster/model',
              '**/features/edit-monster/model.ts',
            ],
            message: 'Import monster editing through features/edit-monster/index.js.',
          },
          {
            group: [
              '**/features/editor/ui/Input',
              '**/features/editor/ui/Input.jsx',
			  '**/features/editor/ui/Input.tsx',
              '**/features/editor/ui/InputView',
			  '**/features/editor/ui/InputView.tsx',
              '**/features/editor/ui/inputTypes',
			  '**/features/editor/ui/inputTypes.ts',
              '**/features/editor/ui/EditableField',
              '**/features/editor/ui/EditableField.jsx',
			  '**/features/editor/ui/EditableField.tsx',
              '**/features/editor/ui/MentionPickerModalContent',
              '**/features/editor/ui/MentionPickerModalContent.jsx',
			  '**/features/editor/ui/MentionPickerModalContent.tsx',
            ],
            message: 'Import editor UI through features/editor/ui/index.js.',
          },
          {
            group: [
              '**/features/notes/ui/AiContextIgnoreButton',
              '**/features/notes/ui/AiContextIgnoreButton.jsx',
              '**/features/notes/ui/AiContextIgnoreButton.tsx',
              '**/features/notes/ui/BulkCollapseButton',
              '**/features/notes/ui/BulkCollapseButton.jsx',
              '**/features/notes/ui/BulkCollapseButton.tsx',
              '**/features/notes/ui/NoteCard',
              '**/features/notes/ui/NoteCard.jsx',
              '**/features/notes/ui/NoteCard.tsx',
              '**/features/notes/ui/aiIgnoredNoteListProps',
              '**/features/notes/ui/aiIgnoredNoteListProps.jsx',
              '**/features/notes/ui/aiIgnoredNoteListProps.tsx',
            ],
            message: 'Import note UI through features/notes/ui/index.js.',
          },
          {
            group: ['**/entities/campaign/api/*', '**/entities/campaign/model/*'],
            message: 'Import the campaign entity through entities/campaign/index.js.',
          },
          {
            group: ['**/entities/spell/api/*', '**/entities/spell/model/*'],
            message: 'Import the spell entity through entities/spell/index.js.',
          },
          {
            group: ['**/entities/bestiary/api/*', '**/entities/bestiary/model/*'],
            message: 'Import the bestiary entity through entities/bestiary/index.js.',
          },
          {
            group: ['**/entities/session/api/*', '**/entities/session/model/*'],
            message: 'Import the session entity through entities/session/index.js.',
          },
          {
            group: ['**/entities/encounter/model/*'],
            message: 'Import the encounter entity through entities/encounter/index.js.',
          },
          {
            group: [
              '**/entities/reference/api/*',
              '**/entities/reference/model/*',
            ],
            message: 'Import the reference entity through entities/reference/index.js.',
          },
          {
            group: ['**/features/editor/model/*'],
            message: 'Import editor behavior through features/editor/model.js.',
          },
          {
            group: ['**/features/settings/model/*'],
            message: 'Import settings behavior through features/settings/index.js.',
          },
          {
            group: [
              '**/features/settings/ui/ColorThemeSwitcher',
              '**/features/settings/ui/ColorThemeSwitcher.jsx',
              '**/features/settings/ui/ColorThemeSwitcher.tsx',
              '**/features/settings/ui/SettingsModalContent',
              '**/features/settings/ui/SettingsModalContent.jsx',
              '**/features/settings/ui/SettingsModalContent.tsx',
              '**/features/settings/ui/CampaignScopeOptions',
              '**/features/settings/ui/CampaignScopeOptions.tsx',
            ],
            message: 'Import settings UI through features/settings/ui/index.js.',
          },
          {
            group: [
              '**/features/rich-content/model/*',
              '**/features/rich-content/ui/*',
            ],
            message: 'Import rich-content through features/rich-content/index.js or its Node-safe model.js facade.',
          },
          {
            group: ['**/shared/model/actions', '**/shared/model/actions.js', '**/shared/model/appStore', '**/shared/model/appStore.js', '**/shared/model/appStore.ts'],
            message: 'Import global app state and actions through shared/model/index.js.',
          },
          {
            group: [
              '**/widgets/campaign-entity-card/model/*',
              '**/widgets/campaign-entity-card/ui/*',
            ],
            message: 'Import campaign entity cards through widgets/campaign-entity-card/index.js or its Node-safe model.js facade.',
          },
          {
            group: [
              '**/widgets/spells-browser/model/*',
              '**/widgets/spells-browser/ui/*',
            ],
            message: 'Import the spells browser through widgets/spells-browser/index.js or its Node-safe model.js facade.',
          },
          {
            group: [
              '**/widgets/bestiary-browser/model/*',
              '**/widgets/bestiary-browser/ui/*',
            ],
            message: 'Import the Bestiary browser through widgets/bestiary-browser/index.js or its Node-safe model.js facade.',
          },
          {
            group: [
              '**/widgets/monster-stat-block/model/*',
              '**/widgets/monster-stat-block/ui/*',
            ],
            message: 'Import monster stat blocks through widgets/monster-stat-block/index.js or its Node-safe model.js facade.',
          },
          {
            group: [
              '**/widgets/rules-reference-modal/model/*',
              '**/widgets/rules-reference-modal/ui/*',
            ],
            message: 'Import rules-reference modal composition through widgets/rules-reference-modal/index.js or its Node-safe model.js facade.',
          },
          {
            group: ['**/widgets/monster-editor-modal/ui/*'],
            message: 'Import composed monster editors through widgets/monster-editor-modal/index.js.',
          },
          {
            group: [
              '**/widgets/campaign-entity-modal/model/*',
              '**/widgets/campaign-entity-modal/ui/*',
            ],
            message: 'Import campaign entity modal composition through widgets/campaign-entity-modal/index.js or its Node-safe model.js facade.',
          },
          {
            group: ['**/widgets/ai-response-modal/ui/*'],
            message: 'Import AI response modal composition through widgets/ai-response-modal/index.js.',
          },
          {
            group: [
              '**/widgets/ai-assistant/model/*',
              '**/widgets/ai-assistant/ui/*',
            ],
            message: 'Import AI assistant composition through widgets/ai-assistant/index.js or its Node-safe model.js facade.',
          },
          {
            group: [
              '**/widgets/campaign-search/model/*',
              '**/widgets/campaign-search/ui/*',
            ],
            message: 'Import campaign search through widgets/campaign-search/index.js or its Node-safe model.js facade.',
          },
          {
            group: [
              '**/widgets/sidebar/model/*',
              '**/widgets/sidebar/ui/*',
            ],
            message: 'Import the sidebar through widgets/sidebar/index.js or its Node-safe model.js facade.',
          },
          {
            group: ['**/pages/campaign/ui/*', '**/pages/campaign/model/*'],
            message: 'Import the campaign page through pages/campaign/index.js.',
          },
          {
            group: ['**/pages/session/ui/*', '**/pages/session/model/*'],
            message: 'Import the session page through pages/session/index.js.',
          },
          {
            group: ['**/pages/encounter/ui/*', '**/pages/encounter/model/*'],
            message: 'Import the encounter page through pages/encounter/index.js.',
          },
          {
            group: [
              '**/shared/ui/Panel',
              '**/shared/ui/Panel.jsx',
              '**/shared/ui/Panel.tsx',
              '**/shared/ui/Button',
              '**/shared/ui/Button.jsx',
              '**/shared/ui/Button.tsx',
              '**/shared/ui/Checkbox',
              '**/shared/ui/Checkbox.jsx',
              '**/shared/ui/Checkbox.tsx',
              '**/shared/ui/Icon',
              '**/shared/ui/Icon.jsx',
              '**/shared/ui/Icon.tsx',
              '**/shared/ui/MultiSelect',
              '**/shared/ui/MultiSelect.jsx',
              '**/shared/ui/MultiSelect.tsx',
              '**/shared/ui/Notification',
              '**/shared/ui/Notification.jsx',
              '**/shared/ui/Notification.tsx',
              '**/shared/ui/Switch',
              '**/shared/ui/Switch.jsx',
              '**/shared/ui/Switch.tsx',
              '**/shared/ui/Select',
              '**/shared/ui/Select.jsx',
              '**/shared/ui/Select.tsx',
              '**/shared/ui/Tooltip',
              '**/shared/ui/Tooltip.jsx',
              '**/shared/ui/Tooltip.tsx',
              '**/shared/ui/CollapseToggleButton',
              '**/shared/ui/CollapseToggleButton.jsx',
              '**/shared/ui/CollapseToggleButton.tsx',
              '**/shared/ui/DraggableList',
              '**/shared/ui/DraggableList.jsx',
              '**/shared/ui/DraggableList.tsx',
              '**/shared/ui/SearchHighlight',
              '**/shared/ui/SearchHighlight.jsx',
              '**/shared/ui/SearchHighlight.tsx',
              '**/shared/ui/ListCard',
              '**/shared/ui/ListCard.jsx',
              '**/shared/ui/ListCard.tsx',
              '**/shared/lib/classNames',
              '**/shared/lib/classNames.js',
              '**/shared/lib/noteUtils',
              '**/shared/lib/noteUtils.js',
              '**/shared/lib/id',
              '**/shared/lib/id.js',
              '**/shared/lib/useDebounce',
              '**/shared/lib/useDebounce.js',
              '**/shared/lib/dice',
              '**/shared/lib/dice.js',
              '**/shared/lib/deepSearch',
              '**/shared/lib/deepSearch.js',
              '**/shared/lib/download',
              '**/shared/lib/download.js',
              '**/shared/lib/formatBytes',
              '**/shared/lib/formatBytes.js',
              '**/shared/lib/json',
              '**/shared/lib/json.js',
              '**/shared/lib/localization',
              '**/shared/lib/localization.js',
              '**/shared/api/httpClient',
              '**/shared/api/httpClient.js',
              '**/shared/api/httpClient.ts',
              '**/shared/lib/navigation',
              '**/shared/lib/navigation.js',
              '**/shared/lib/navigation.ts',
              '**/shared/lib/domNavigation',
              '**/shared/lib/domNavigation.js',
              '**/shared/lib/undoRedo',
              '**/shared/lib/undoRedo.js',
            ],
            message: 'Import shared modules through their public index.js API.',
          },
          {
            group: [
              '**/components/ImageGallery',
              '**/components/ImageGallery.jsx',
              '**/components/ImageTargetSettings',
              '**/components/ImageTargetSettings.jsx',
              '**/components/form/ImageDropzone',
              '**/components/form/ImageDropzone.jsx',
              '**/components/form/ImageAssetField',
              '**/components/form/ImageAssetField.jsx',
              '**/hooks/useImageGallery',
              '**/hooks/useImageGallery.js',
            ],
            message: 'Legacy image paths were retired; use features/images/index.js.',
          },
          {
            group: [
              '**/components/common/Panel',
              '**/components/common/Panel.jsx',
              '**/components/common/Icon',
              '**/components/common/Icon.jsx',
              '**/components/common/Tooltip',
              '**/components/common/Tooltip.jsx',
              '**/components/common/Notification',
              '**/components/common/Notification.jsx',
              '**/components/form/Switch',
              '**/components/form/Switch.jsx',
              '**/components/form/Button',
              '**/components/form/Button.jsx',
              '**/components/form/Checkbox',
              '**/components/form/Checkbox.jsx',
              '**/components/form/MultiSelect',
              '**/components/form/MultiSelect.jsx',
              '**/components/form/Select',
              '**/components/form/Select.jsx',
              '**/utils/classNames',
              '**/utils/classNames.js',
              '**/utils/noteUtils',
              '**/utils/noteUtils.js',
              '**/models/CharacterCardModel',
              '**/models/CharacterCardModel.js',
              '**/models/LocationCardModel',
              '**/models/LocationCardModel.js',
              '**/models/cardNoteModelUtils',
              '**/models/cardNoteModelUtils.js',
              '**/components/CharacterCard',
              '**/components/CharacterCard.jsx',
              '**/components/LocationCard',
              '**/components/LocationCard.jsx',
              '**/components/CreateCharacterButton',
              '**/components/CreateCharacterButton.jsx',
              '**/components/CreateLocationButton',
              '**/components/CreateLocationButton.jsx',
              '**/components/SpellCard',
              '**/components/SpellCard.jsx',
              '**/models/SpellCardModel',
              '**/models/SpellCardModel.js',
              '**/models/MonsterStatBlockModel',
              '**/models/MonsterStatBlockModel.js',
              '**/utils/bestiary',
              '**/utils/bestiary.js',
              '**/utils/encounters',
              '**/utils/encounters.js',
              '**/utils/campaignGraph',
              '**/utils/campaignGraph.js',
              '**/utils/campaignGraphLayout',
              '**/utils/campaignGraphLayout.js',
              '**/utils/aiAttachments',
              '**/utils/aiAttachments.js',
              '**/utils/aiDiff',
              '**/utils/aiDiff.js',
              '**/utils/aiModels',
              '**/utils/aiModels.js',
              '**/utils/aiResponseHelpers',
              '**/utils/aiResponseHelpers.js',
              '**/utils/conditions',
              '**/utils/conditions.js',
              '**/utils/contentTokens',
              '**/utils/contentTokens.js',
              '**/utils/parser',
              '**/utils/parser.jsx',
              '**/utils/parserTags',
              '**/utils/parserTags.js',
              '**/utils/referencePreview',
              '**/utils/referencePreview.js',
              '**/utils/referenceResolvers',
              '**/utils/referenceResolvers.js',
              '**/utils/searchHighlight',
              '**/utils/searchHighlight.jsx',
              '**/utils/sourceIgnore',
              '**/utils/sourceIgnore.js',
              '**/utils/sourceNames',
              '**/utils/sourceNames.js',
              '**/utils/spellMeta',
              '**/utils/spellMeta.js',
              '**/utils/mentionEditor',
              '**/utils/mentionEditor.js',
              '**/utils/mentionPicker',
              '**/utils/mentionPicker.js',
              '**/services/conditions',
              '**/services/conditions.js',
              '**/services/diseases',
              '**/services/diseases.js',
              '**/services/senses',
              '**/services/senses.js',
              '**/services/skills',
              '**/services/skills.js',
              '**/services/variantRules',
              '**/services/variantRules.js',
              '**/services/referencePreview',
              '**/services/referencePreview.js',
              '**/services/referenceResolvers',
              '**/services/referenceResolvers.js',
              '**/services/entities',
              '**/services/entities.js',
              '**/services/localization',
              '**/services/localization.js',
              '**/services/realtimeSync',
              '**/services/realtimeSync.js',
              '**/services/uiSettings',
              '**/services/uiSettings.js',
              '**/actions/app',
              '**/actions/app.js',
              '**/store/appStore',
              '**/store/appStore.js',
              '**/renderers/contentRenderer',
              '**/renderers/contentRenderer.jsx',
              '**/models/CampaignViewModel',
              '**/models/CampaignViewModel.js',
              '**/models/SessionViewModel',
              '**/models/SessionViewModel.js',
              '**/utils/id',
              '**/utils/id.js',
              '**/hooks/useDebounce',
              '**/hooks/useDebounce.js',
              '**/components/CampaignView',
              '**/components/CampaignView.jsx',
              '**/hooks/useCampaignView',
              '**/hooks/useCampaignView.js',
              '**/components/SessionView',
              '**/components/SessionView.jsx',
              '**/hooks/useSessionView',
              '**/hooks/useSessionView.js',
              '**/components/EncounterView',
              '**/components/EncounterView.jsx',
              '**/hooks/useEncounterView',
              '**/hooks/useEncounterView.js',
              '**/components/Spells',
              '**/components/Spells.jsx',
              '**/components/MonsterStatBlock',
              '**/components/MonsterStatBlock.jsx',
              '**/components/DiceCalculator',
              '**/components/DiceCalculator.jsx',
              '**/components/DiceCalculator.tsx',
              '**/components/DiceProbabilityModalContent',
              '**/components/DiceProbabilityModalContent.jsx',
              '**/components/DiceProbabilityModalContent.tsx',
              '**/components/common/RollDice',
              '**/components/common/RollDice.jsx',
              '**/components/common/RollDice.tsx',
              '**/utils/dice',
              '**/utils/dice.js',
              '**/utils/deepSearch',
              '**/utils/deepSearch.js',
              '**/utils/download',
              '**/utils/download.js',
              '**/utils/formatBytes',
              '**/utils/formatBytes.js',
              '**/utils/json',
              '**/utils/json.js',
              '**/utils/navigation',
              '**/utils/navigation.js',
              '**/utils/domNavigation',
              '**/utils/domNavigation.js',
              '**/utils/undoRedo',
              '**/utils/undoRedo.js',
              '**/components/common/RulesLink',
              '**/components/common/RulesLink.jsx',
              '**/components/modals/openRulesReferenceModal',
              '**/components/modals/openRulesReferenceModal.jsx',
              '**/components/modals/RulesReferenceModalContent',
              '**/components/modals/RulesReferenceModalContent.jsx',
              '**/components/modals/RulesReferenceModalHost',
              '**/components/modals/RulesReferenceModalHost.jsx',
              '**/components/common/CollapseToggleButton',
              '**/components/common/CollapseToggleButton.jsx',
              '**/components/common/DraggableList',
              '**/components/common/DraggableList.jsx',
              '**/components/common/ListCard',
              '**/components/common/ListCard.jsx',
              '**/components/common/EntityLink',
              '**/components/common/EntityLink.jsx',
              '**/components/common/EntityLinkContext',
              '**/components/common/EntityLinkContext.jsx',
              '**/components/common/EntityLinkIdentity',
              '**/components/common/EntityLinkIdentity.js',
              '**/components/common/EntityModal',
              '**/components/common/EntityModal.jsx',
              '**/components/common/entityLinkModalUtils',
              '**/components/common/entityLinkModalUtils.js',
              '**/components/common/CampaignEntityModalProvider',
              '**/components/common/CampaignEntityModalProvider.jsx',
              '**/components/common/Modal',
              '**/components/common/Modal.jsx',
              '**/components/common/MessageBox',
              '**/components/common/MessageBox.jsx',
              '**/components/ai/AiAttachmentControls',
              '**/components/ai/AiAttachmentControls.jsx',
              '**/components/ai/AiResponseModal',
              '**/components/ai/AiResponseModal.jsx',
              '**/components/ai/AiAssistantPanel',
              '**/components/ai/AiAssistantPanel.jsx',
              '**/components/ai/AiImagePromptPickerModal',
              '**/components/ai/AiImagePromptPickerModal.jsx',
              '**/components/session/SceneCardFields',
              '**/components/session/SceneCardFields.jsx',
              '**/components/session/SceneCardHeader',
              '**/components/session/SceneCardHeader.jsx',
              '**/components/session/SceneCardMedia',
              '**/components/session/SceneCardMedia.jsx',
              '**/components/session/TodoItem',
              '**/components/session/TodoItem.jsx',
              '**/components/session/TodoSection',
              '**/components/session/TodoSection.jsx',
              '**/components/campaign/CampaignNotesGraph',
              '**/components/campaign/CampaignNotesGraph.jsx',
              '**/components/campaign/GlobalSearchModal',
              '**/components/campaign/GlobalSearchModal.jsx',
              '**/components/campaign/PartialArchiveModal',
              '**/components/campaign/PartialArchiveModal.jsx',
              '**/components/MainContent',
              '**/components/MainContent.jsx',
              '**/components/ProjectGuide',
              '**/components/ProjectGuide.jsx',
              '**/components/Sidebar',
              '**/components/Sidebar.jsx',
              '**/components/ColorThemeSwitcher',
              '**/components/ColorThemeSwitcher.jsx',
              '**/components/modals/SettingsModalContent',
              '**/components/modals/SettingsModalContent.jsx',
              '**/components/modals/SettingsModalContent.tsx',
              '**/components/form/Input',
              '**/components/form/Input.jsx',
              '**/components/form/EditableField',
              '**/components/form/EditableField.jsx',
              '**/components/modals/MentionPickerModalContent',
              '**/components/modals/MentionPickerModalContent.jsx',
              '**/components/common/AiContextIgnoreButton',
              '**/components/common/AiContextIgnoreButton.jsx',
              '**/components/common/BulkCollapseButton',
              '**/components/common/BulkCollapseButton.jsx',
              '**/components/common/NoteCard',
              '**/components/common/NoteCard.jsx',
              '**/components/common/aiIgnoredNoteListProps',
              '**/components/common/aiIgnoredNoteListProps.jsx',
              '**/components/common/ClickToCopy',
              '**/components/common/ClickToCopy.jsx',
              '**/components/common/StatusBadge',
              '**/components/common/StatusBadge.jsx',
              '**/components/modals/AddMonsterToEncounterModalContent',
              '**/components/modals/AddMonsterToEncounterModalContent.jsx',
              '**/components/modals/AddMonsterToEncounterModalContent.tsx',
              '**/components/modals/CreateCampaignModalContent',
              '**/components/modals/CreateCampaignModalContent.jsx',
              '**/components/modals/PlayerQuestionsModalContent',
              '**/components/modals/PlayerQuestionsModalContent.jsx',
            ],
            message: 'Legacy primitive paths were retired; use shared/ui/index.js.',
          },
        ],
      }]
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      'no-restricted-imports': ['error', {
        patterns: TYPESCRIPT_PUBLIC_API_PATTERNS,
      }],
    },
  },
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    ignores: ['src/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
  {
    files: ['src/**/*.{js,jsx,ts,tsx}'],
    plugins: {
      'fsd-boundaries': FSD_BOUNDARY_PLUGIN,
    },
    rules: {
      'fsd-boundaries/public-entry-imports': 'error',
      'fsd-boundaries/app-store-runtime-owner': 'error',
    },
  },
  {
    files: ['src/features/settings/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/settings-store-facade': 'error',
    },
  },
  {
    files: ['src/features/notes/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/notes-store-facade': 'error',
    },
  },
  {
    files: ['src/features/player-questions/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/player-questions-store-facade': 'error',
    },
  },
  {
    files: ['src/features/campaign-entity/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/campaign-entity-store-facade': 'error',
    },
  },
  {
    files: ['src/features/encounter-editor/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/encounter-editor-store-facade': 'error',
    },
  },
  {
    files: ['src/features/rules-reference/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/rules-reference-store-facade': 'error',
    },
  },
  {
    files: ['src/features/ai/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/ai-store-facade': 'error',
    },
  },
  {
    files: ['src/features/editor/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/editor-store-facade': 'error',
    },
  },
  {
    files: ['src/features/dice/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/dice-store-facade': 'error',
    },
  },
  {
    files: ['src/features/images/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/images-store-facade': 'error',
    },
  },
  {
    files: ['src/widgets/campaign-entity-card/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/campaign-entity-card-store-facade': 'error',
    },
  },
  {
    files: ['src/widgets/campaign-search/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/campaign-search-store-facade': 'error',
    },
  },
  {
    files: ['src/widgets/campaign-entity-modal/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/campaign-entity-modal-store-facade': 'error',
    },
  },
  {
    files: ['src/widgets/rules-reference-modal/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/rules-reference-modal-store-facade': 'error',
    },
  },
  {
    files: ['src/widgets/spells-browser/**/*.{js,jsx,ts,tsx}'],
    rules: {
      'fsd-boundaries/spells-browser-store-facade': 'error',
    },
  },
  {
    files: [
      'src/features/**/*.{js,jsx,ts,tsx}',
      'src/widgets/**/*.{js,jsx,ts,tsx}',
    ],
    rules: {
      'fsd-boundaries/same-layer-file-edges': 'error',
    },
  },
  {
    files: ['src/entities/campaign/model/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': ['error', {
        patterns: CAMPAIGN_MODEL_IMPORT_PATTERNS,
      }],
    },
  },
  {
    files: [
      'src/entities/reference/model/{conditions,diseases,senses,skills,variantRules}.ts',
    ],
    rules: {
      'no-restricted-imports': ['error', {
        patterns: REFERENCE_LOADER_IMPORT_PATTERNS,
      }],
    },
  },
];
