import { IMAGE_GALLERY_CATEGORIES } from "../imageGalleryConfig.js";
import type { UseImageGalleryOptions } from "./contracts.ts";
import { useImageGalleryLoading } from "./useImageGalleryLoading.ts";
import { useImageGalleryLocation } from "./useImageGalleryLocation.ts";
import { useImageGalleryMutations } from "./useImageGalleryMutations.ts";
import { useImageGallerySelection } from "./useImageGallerySelection.ts";

export default function useImageGallery({
	isOpen,
	initialSource,
	initialCategory,
	initialSubcategory,
}: UseImageGalleryOptions) {
	const location = useImageGalleryLocation();
	const loadingState = useImageGalleryLoading({
		activeSearchQuery: location.activeSearchQuery,
		contentScope: location.contentScope,
		debouncedSearchQuery: location.debouncedSearchQuery,
		ignoreSourcesList: location.ignoreSourcesList,
		initialCategory,
		initialSource,
		initialSubcategory,
		isGeneralTokens: location.isGeneralTokens,
		isOpen,
		isScopedContent: location.isScopedContent,
		normalizedSearchQuery: location.normalizedSearchQuery,
		selectedCat: location.selectedCat,
		selectedSource: location.selectedSource,
		selectedSub: location.selectedSub,
		setSelectedCat: location.setSelectedCat,
		setSelectedSource: location.setSelectedSource,
		setSelectedSub: location.setSelectedSub,
	});
	const selection = useImageGallerySelection({
		dynamicSubs: loadingState.dynamicSubs,
		images: loadingState.images,
		isGeneralTokens: location.isGeneralTokens,
		isScopedContent: location.isScopedContent,
		normalizedSearchQuery: location.normalizedSearchQuery,
		officialRootSubs: loadingState.officialRootSubs,
		officialSubs: loadingState.officialSubs,
		selectedCat: location.selectedCat,
		selectedSource: location.selectedSource,
		selectedSub: location.selectedSub,
	});
	const mutations = useImageGalleryMutations({
		clearSelection: selection.clearSelection,
		contentScope: location.contentScope,
		getMovableSelectedItems: selection.getMovableSelectedItems,
		isOpen,
		isReadonlyCurrentFolder: selection.isReadonlyCurrentFolder,
		isReadonlyImage: selection.isReadonlyImage,
		isReadonlySub: selection.isReadonlySub,
		loadImages: loadingState.loadImages,
		loadStorageStats: loadingState.loadStorageStats,
		loadSubcategories: loadingState.loadSubcategories,
		selectedCat: location.selectedCat,
		selectedFilenames: selection.selectedFilenames,
		selectedSource: location.selectedSource,
		selectedSub: location.selectedSub,
		selectedSubs: selection.selectedSubs,
		setLoading: loadingState.setLoading,
		setSelectedFilenames: selection.setSelectedFilenames,
		setSelectedSub: location.setSelectedSub,
		setSelectedSubs: selection.setSelectedSubs,
	});

	return {
		campaigns: loadingState.campaigns,
		categories: IMAGE_GALLERY_CATEGORIES,
		selectedSource: location.selectedSource,
		setSelectedSource: location.setSelectedSource,
		selectedCat: location.selectedCat,
		setSelectedCat: location.setSelectedCat,
		selectedSub: location.selectedSub,
		setSelectedSub: location.setSelectedSub,
		images: loadingState.images,
		searchQuery: location.searchQuery,
		setSearchQuery: location.setSearchQuery,
		contentScope: location.contentScope,
		setContentScope: location.setContentScope,
		isGlobalSearch: location.isGlobalSearch,
		isSearchResults: location.isSearchResults,
		isReadonlyCurrentFolder: selection.isReadonlyCurrentFolder,
		isReadonlyPath: selection.isReadonlyPath,
		storageStats: loadingState.storageStats,
		selectedFilenames: selection.selectedFilenames,
		selectedSubs: selection.selectedSubs,
		loading: loadingState.loading,
		isCreatingSub: mutations.isCreatingSub,
		setIsCreatingSub: mutations.setIsCreatingSub,
		newSubName: mutations.newSubName,
		setNewSubName: mutations.setNewSubName,
		isDraggingOver: mutations.isDraggingOver,
		setIsDraggingOver: mutations.setIsDraggingOver,
		dragSource: mutations.dragSource,
		dragOverTarget: mutations.dragOverTarget,
		setDragOverTarget: mutations.setDragOverTarget,
		hasSelection: selection.hasSelection,
		clearSelection: selection.clearSelection,
		selectImageByName: selection.selectImageByName,
		allSubs: selection.allSubs,
		subDetails: loadingState.subDetails,
		handleCreateSub: mutations.handleCreateSub,
		handleBulkDelete: mutations.handleBulkDelete,
		handleMoveSelection: mutations.handleMoveSelection,
		handleFileUpload: mutations.handleFileUpload,
		handleDrop: mutations.handleDrop,
		handleItemClick: selection.handleItemClick,
		toggleSelect: selection.toggleSelect,
		handleRenameSub: mutations.handleRenameSub,
		handleDragStart: mutations.handleDragStart,
		handleDragEnd: mutations.handleDragEnd,
		getCleanName: mutations.getCleanName,
		handleRenameImage: mutations.handleRenameImage,
		isProtectedSystemSub: selection.isProtectedSystemSub,
		isOfficialSub: selection.isOfficialSub,
		isReadonlySub: selection.isReadonlySub,
		isReadonlyImage: selection.isReadonlyImage,
	};
}
